#!/usr/bin/env python3
"""Generate docs/arch-coverage.md from arch_table.py intersected with the
installed mlx-lm.

Walks ``mlx_lm/models/*.py`` for modules defining ``class Model`` (the loadable
model_types), intersects with ``arch_table.ARCH_TABLE``, and writes a Markdown
status table. ``--check`` verifies the committed doc is up to date (CI);
``--strict`` exits non-zero on an inconsistency - an arch with a synthesizer
whose mlx-lm ``class Model`` is missing, or that isn't in the table.

  python scripts/check-coverage.py            # (re)write docs/arch-coverage.md
  python scripts/check-coverage.py --check     # fail if the doc is stale
  python scripts/check-coverage.py --strict    # fail on a coverage inconsistency
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Run from a source checkout without installing the package.
_REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO))

from gmlx import arch_table, config_synth  # noqa: E402


def mlx_lm_model_types() -> dict[str, bool]:
    """Map every ``mlx_lm/models/<stem>.py`` to whether it defines ``class
    Model`` (the ~10 utility modules without one are the non-loadable filter)."""
    import mlx_lm.models as models_pkg

    models_dir = Path(models_pkg.__file__).parent
    out: dict[str, bool] = {}
    for path in sorted(models_dir.glob("*.py")):
        if path.stem.startswith("_"):
            continue
        out[path.stem] = "class Model" in path.read_text(encoding="utf-8")
    return out


def _has_model_class(e, have_class: dict[str, bool]) -> bool:
    """Does the *installed* backend package ship ``class Model`` for this arch?
    Almost every arch is mlx-lm; a few are mlx-vlm or mlx-embeddings, so consult
    the right package (the embeddings helper also applies the module-name alias,
    e.g. gemma_embedding -> gemma3_text)."""
    if e.backend == "mlx-vlm":
        return arch_table.mlx_vlm_has_model(e.model_type)
    if e.backend == "mlx-embeddings":
        return arch_table.mlx_embeddings_has_model(e.model_type)
    if e.model_type in arch_table._VENDORED_MLX_LM_MODULES:
        # gmlx vendors the module (unmerged mlx-lm PR); the loader grafts
        # it into mlx_lm.models, so it counts as backed.
        return arch_table.mlx_lm_has_model(e.model_type)
    return have_class.get(e.model_type, False)


def build_rows():
    have_class = mlx_lm_model_types()
    rows = []
    for arch, e in sorted(arch_table.ARCH_TABLE.items()):
        cls = _has_model_class(e, have_class)
        synth = arch_table.has_synth(arch)
        if arch in config_synth.DISABLED_ARCHES:
            status = "disabled (no known-good GGUF)"
        elif not cls:
            status = f"needs {e.backend}"
        elif synth:
            status = "loadable"
        else:
            status = "needs synth (hf_source)"
        rows.append({
            "arch": arch, "model_type": e.model_type, "cls": cls,
            "remap": "yes" if e.remap_alias else "canonical",
            "synth": synth, "status": status, "notes": e.notes,
        })
    return rows, have_class


def render_md(rows) -> str:
    chk = lambda b: "yes" if b else "no"  # noqa: E731
    loadable = sum(1 for r in rows if r["status"] == "loadable")
    lines = [
        "# GGUF architecture coverage",
        "",
        "**GENERATED by `scripts/check-coverage.py` - do not edit by hand.**",
        "",
        "A GGUF loads iff gmlx maps its `general.architecture` to a `model_type` "
        "with a model class in one of its installed backend packages (usually "
        "mlx-lm; a few archs are backed by mlx-vlm (e.g. DiffusionGemma) or "
        "mlx-embeddings (gemma-embedding)) "
        "and a config synthesizer exists (or `hf_source` supplies a config.json).",
        "",
        f"**{loadable} / {len(rows)} mapped architectures load end-to-end "
        "today** (no `hf_source` needed).",
        "",
        "| GGUF arch | model_type | model class | remap | synth | status | notes |",
        "|-----------|------------|:-----------:|-------|:-----:|--------|-------|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['arch']}` | `{r['model_type']}` | {chk(r['cls'])} | "
            f"{r['remap']} | {chk(r['synth'])} | {r['status']} | {r['notes']} |")
    lines += [
        "",
        "Columns: **remap** - `yes` if an `ARCH_ALIAS` entry exists, else "
        "`canonical`. **synth** - a config synthesizer is implemented "
        "(`config_synth.supported_arches()`). **status** - `loadable` "
        "(class + synth), `needs synth (hf_source)` (class but no synth), "
        "`needs <backend>` (no class in the installed backend package), `disabled "
        "(no known-good GGUF)` (code complete but every available GGUF is "
        "broken at conversion, so the gate refuses it).",
        "",
    ]
    return "\n".join(lines)


def strict_problems(rows, have_class) -> list[str]:
    """Coverage inconsistencies that should fail CI."""
    problems = []
    for arch in sorted(config_synth.supported_arches()):
        e = arch_table.ARCH_TABLE.get(arch)
        if e is None:
            problems.append(
                f"{arch!r}: has a synthesizer but is missing from ARCH_TABLE")
        elif not _has_model_class(e, have_class):
            problems.append(
                f"{arch!r}: synthesizer present but the installed {e.backend} has "
                f"no `class Model` for model_type {e.model_type!r}")
    return problems


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--output", default=str(_REPO / "docs" / "arch-coverage.md"),
                    help="output path (default: docs/arch-coverage.md)")
    ap.add_argument("--check", action="store_true",
                    help="don't write; exit non-zero if the doc is stale")
    ap.add_argument("--strict", action="store_true",
                    help="exit non-zero on a coverage inconsistency")
    args = ap.parse_args(argv)

    rows, have_class = build_rows()
    md = render_md(rows)
    out = Path(args.output)

    rc = 0
    if args.strict:
        problems = strict_problems(rows, have_class)
        if problems:
            print("COVERAGE INCONSISTENCIES:", file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            rc = 1

    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != md:
            print(f"{out} is stale - re-run scripts/check-coverage.py",
                  file=sys.stderr)
            return rc or 1
        print(f"{out} is up to date ({len(rows)} architectures)")
        return rc

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")
    loadable = sum(1 for r in rows if r["status"] == "loadable")
    print(f"wrote {out}: {len(rows)} architectures, {loadable} loadable")
    return rc


if __name__ == "__main__":
    sys.exit(main())
